---
title: "Research"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "100%",
               dpi = 200,
               fig.align = "center")  
```

<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

## Working Papers

### In Search of Working Time? Hours Constraints, Firms and Mobility 

<a href="pdf/draft_hc.pdf">[Draft]</a> 
<a href="https://www.parisschoolofeconomics.eu/en/publications-hal/in-search-of-working-time-hours-constraints-firms-and-mobility/">[PSE WP]</a>

<button class="button_link" role="button" onclick="hide_buttons('abstract_hc')">Abstract</button>
<div id="abstract_hc" style="display:none;">
Can workers find a job with their ideal working hours? This paper provides novel empirical evidence on hours constraints, i.e. barriers for workers to work their desired hours at a given wage rate, by linking self-reported hour preferences from large-scale survey data with administrative employer-employee data between 2003 and 2023. Twenty percent of French salaried workers report wanting to increase their hours at their given wage. Leveraging the panel dimension of my data, I show that constrained workers experience larger increases in hours and earnings than other workers by switching employers. However, most constrained workers remain unable to adjust their hours to their desired level within 3 years after their report. Next, I develop a revealed preference method to quantify welfare effects associated with constraints and find that workers would on average accept a 10% reduction in hourly wages to work in a job offering their desired number of hours. The results highlight the important role of hours worked as a job amenity in shaping labor market sorting. 
</div> 

<br />


### Are Workers Who Misunderstand Their Working Contract Worse Off? 

with [Thomas Breda](https://www.parisschoolofeconomics.com/breda-thomas/index_en.html) and [Vladimir Pecheu](https://vladimirpecheu.com/) 

*R&R at Labour Economics*

<a href="pdf/draft_forfaits_v2.pdf">[Draft]</a>

<button class="button_link" role="button" onclick="hide_buttons('abstract_forfait')">Abstract</button> 
<div id="abstract_forfait" style="display:none;">
This paper examines workers' awareness of their contractual working time arrangements and its relation with labour market outcomes. Combining administrative and survey data at the individual level, we construct a new and unique data set which shows that nearly 20\% of the workforce mistakenly report that they work under day contracts, with no monitoring of hours, while they are actually paid through a standard hours contract. This reveals that many workers with various profiles may be misinformed about the legal environment governing something as fundamental as their working time. We show that these misreporting workers differ from classic workers in terms of working conditions: they perform more unpaid overtime hours but have a higher wage rate per contractual hour, so that their true compensation per hour worked is similar.  This suggests    that firms do not comply with formal regulations with uninformed workers but do neither take advantage of  their misunderstanding  to extract rents.
</div> 

<br />

###   Le Développement des Nouveaux Indépendants Est-Il un Facteur de Tension sur le Marché du Travail Salarié ? 

with [Philippe Askenazy](https://cmh.ens.fr/author/philippe-askenazy/) and [Christine Erhel](https://ceet.cnam.fr/le-ceet/chercheur-euse-s/christine-erhel-lirsa-ceet--988265.kjsp), Connaissance de l'Emploi n°203, December 2024.

<a href="pdf/CDE_203_Independants.pdf">[CDE WP]</a>

## Work In Progress

### The Role of Hours Constraints in the Child Penalty: Evidence from Germany

*Draft available upon request*

<button class="button_link" role="button" onclick="hide_buttons('abstract_cp')">Abstract</button>
<div id="abstract_cp" style="display:none;">
A large literature has settled the existence of a child penalty on women's labor market outcomes. Previous studies estimate that one third of the gap in earnings lies in an hours component, in particular through women's shifts to part-time work at childbirth. Surprisingly, this hours gap persists in the long run, even once their children are grown up. This paper investigates the role played by hours constraints, i.e. employer-driven frictions that prevent individuals from working their preferred hours, in shaping the hours child penalty. Drawing on data from the German Socio-Economic Panel (GSOEP), which captures both actual and desired hours, I decompose the child penalty into two components reflecting, respectively, labor supply preferences and hours constraints. On average, hours constraints appear to play no significant role, but this masks important heterogeneity: childbirth doubles the share of underemployed mothers, and in this group, hours constraints account for 40% of the hours penalty.
</div> 

<br />

### Job Search and Involuntary Part-Time Work

<br />

## Policy (in French)

-   [Baisse de la Productivité en France : Echec en « maths » ?](https://www.cae-eco.fr/staticfiles/pdf/cae_Focus091.pdf) (Declining Productivity in France : A "Math" Problem?), Focus du CAE no. 091-2022, September 2022.
-   [Activité Partielle et Situation Pré-Crise des Entreprises](https://www.cae-eco.fr/staticfiles/pdf/cae-focus082.pdf) (Short-Time Work and the Pre-Crisis Situation of Firms), Focus du CAE n°082-2022, March 2022.
-   [Immigration et Difficultés de Recrutement](https://www.cae-eco.fr/staticfiles/pdf/cae-focus073(2).pdf) (Immigration and Recruitment Difficulties), Focus du CAE n°073-2021, November 2021. 

## PhD Manuscript

<a href="pdf/PhD_Manuscript.pdf">[Manuscript]</a>


